apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
  labels:
    app: analyzer
spec:
  selector:
    matchLabels:
      app: analyzer
  replicas: 1
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
      - name: analyzer
        image: ibmcom/analyzer:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: TONE_ANALYZER_URL
          value: "gateway-wdc.watsonplatform.net/tone-analyzer/api"
        #- name: TONE_ANALYZER_APIKEY
        #  value: <REPLACE>
        - name: USE_HTTPS
          value: "True"
        ports:
        - containerPort: 5000
          name: http
